# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import gql_service_pb2 as gql__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gql_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionServiceStub(object):
    """============================================================================
    SessionService
    Manages session lifecycle and configuration.
    Errors are returned as gRPC Status codes (UNAUTHENTICATED, NOT_FOUND, etc.)
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/gql.SessionService/Handshake',
                request_serializer=gql__service__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=gql__service__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/gql.SessionService/Configure',
                request_serializer=gql__service__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=gql__service__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/gql.SessionService/Reset',
                request_serializer=gql__service__pb2.ResetRequest.SerializeToString,
                response_deserializer=gql__service__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/gql.SessionService/Close',
                request_serializer=gql__service__pb2.CloseRequest.SerializeToString,
                response_deserializer=gql__service__pb2.CloseResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/gql.SessionService/Ping',
                request_serializer=gql__service__pb2.PingRequest.SerializeToString,
                response_deserializer=gql__service__pb2.PongResponse.FromString,
                _registered_method=True)


class SessionServiceServicer(object):
    """============================================================================
    SessionService
    Manages session lifecycle and configuration.
    Errors are returned as gRPC Status codes (UNAUTHENTICATED, NOT_FOUND, etc.)
    ============================================================================

    """

    def Handshake(self, request, context):
        """Establish a session. Negotiates protocol version and authenticates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Configure session state (schema, graph, timezone, parameters).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset session state to defaults.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Terminate the session. Rolls back any active transaction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check and keepalive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=gql__service__pb2.HandshakeRequest.FromString,
                    response_serializer=gql__service__pb2.HandshakeResponse.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=gql__service__pb2.ConfigureRequest.FromString,
                    response_serializer=gql__service__pb2.ConfigureResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=gql__service__pb2.ResetRequest.FromString,
                    response_serializer=gql__service__pb2.ResetResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=gql__service__pb2.CloseRequest.FromString,
                    response_serializer=gql__service__pb2.CloseResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=gql__service__pb2.PingRequest.FromString,
                    response_serializer=gql__service__pb2.PongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gql.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gql.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService(object):
    """============================================================================
    SessionService
    Manages session lifecycle and configuration.
    Errors are returned as gRPC Status codes (UNAUTHENTICATED, NOT_FOUND, etc.)
    ============================================================================

    """

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.SessionService/Handshake',
            gql__service__pb2.HandshakeRequest.SerializeToString,
            gql__service__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.SessionService/Configure',
            gql__service__pb2.ConfigureRequest.SerializeToString,
            gql__service__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.SessionService/Reset',
            gql__service__pb2.ResetRequest.SerializeToString,
            gql__service__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.SessionService/Close',
            gql__service__pb2.CloseRequest.SerializeToString,
            gql__service__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.SessionService/Ping',
            gql__service__pb2.PingRequest.SerializeToString,
            gql__service__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GqlServiceStub(object):
    """============================================================================
    GqlService
    Executes GQL statements and manages transactions.
    Errors are returned as GQLSTATUS codes in the response payload.
    gRPC status is always OK unless there is a transport-level failure.
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_stream(
                '/gql.GqlService/Execute',
                request_serializer=gql__service__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=gql__service__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.BeginTransaction = channel.unary_unary(
                '/gql.GqlService/BeginTransaction',
                request_serializer=gql__service__pb2.BeginRequest.SerializeToString,
                response_deserializer=gql__service__pb2.BeginResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/gql.GqlService/Commit',
                request_serializer=gql__service__pb2.CommitRequest.SerializeToString,
                response_deserializer=gql__service__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.Rollback = channel.unary_unary(
                '/gql.GqlService/Rollback',
                request_serializer=gql__service__pb2.RollbackRequest.SerializeToString,
                response_deserializer=gql__service__pb2.RollbackResponse.FromString,
                _registered_method=True)


class GqlServiceServicer(object):
    """============================================================================
    GqlService
    Executes GQL statements and manages transactions.
    Errors are returned as GQLSTATUS codes in the response payload.
    gRPC status is always OK unless there is a transport-level failure.
    ============================================================================

    """

    def Execute(self, request, context):
        """Execute any GQL statement. Returns a stream of response frames:
        1. ResultHeader  (column metadata or result type indicator)
        2. RowBatch*     (zero or more batches of rows)
        3. ResultSummary (completion status, row count, diagnostics)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginTransaction(self, request, context):
        """Begin an explicit transaction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Commit the active transaction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Roll back the active transaction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GqlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=gql__service__pb2.ExecuteRequest.FromString,
                    response_serializer=gql__service__pb2.ExecuteResponse.SerializeToString,
            ),
            'BeginTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginTransaction,
                    request_deserializer=gql__service__pb2.BeginRequest.FromString,
                    response_serializer=gql__service__pb2.BeginResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=gql__service__pb2.CommitRequest.FromString,
                    response_serializer=gql__service__pb2.CommitResponse.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=gql__service__pb2.RollbackRequest.FromString,
                    response_serializer=gql__service__pb2.RollbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gql.GqlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gql.GqlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GqlService(object):
    """============================================================================
    GqlService
    Executes GQL statements and manages transactions.
    Errors are returned as GQLSTATUS codes in the response payload.
    gRPC status is always OK unless there is a transport-level failure.
    ============================================================================

    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gql.GqlService/Execute',
            gql__service__pb2.ExecuteRequest.SerializeToString,
            gql__service__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.GqlService/BeginTransaction',
            gql__service__pb2.BeginRequest.SerializeToString,
            gql__service__pb2.BeginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.GqlService/Commit',
            gql__service__pb2.CommitRequest.SerializeToString,
            gql__service__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.GqlService/Rollback',
            gql__service__pb2.RollbackRequest.SerializeToString,
            gql__service__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DatabaseServiceStub(object):
    """============================================================================
    DatabaseService
    Manages database lifecycle. Requires appropriate privileges.
    Errors are returned as gRPC Status codes.
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDatabases = channel.unary_unary(
                '/gql.DatabaseService/ListDatabases',
                request_serializer=gql__service__pb2.ListDatabasesRequest.SerializeToString,
                response_deserializer=gql__service__pb2.ListDatabasesResponse.FromString,
                _registered_method=True)
        self.CreateDatabase = channel.unary_unary(
                '/gql.DatabaseService/CreateDatabase',
                request_serializer=gql__service__pb2.CreateDatabaseRequest.SerializeToString,
                response_deserializer=gql__service__pb2.CreateDatabaseResponse.FromString,
                _registered_method=True)
        self.DeleteDatabase = channel.unary_unary(
                '/gql.DatabaseService/DeleteDatabase',
                request_serializer=gql__service__pb2.DeleteDatabaseRequest.SerializeToString,
                response_deserializer=gql__service__pb2.DeleteDatabaseResponse.FromString,
                _registered_method=True)
        self.GetDatabaseInfo = channel.unary_unary(
                '/gql.DatabaseService/GetDatabaseInfo',
                request_serializer=gql__service__pb2.GetDatabaseInfoRequest.SerializeToString,
                response_deserializer=gql__service__pb2.GetDatabaseInfoResponse.FromString,
                _registered_method=True)


class DatabaseServiceServicer(object):
    """============================================================================
    DatabaseService
    Manages database lifecycle. Requires appropriate privileges.
    Errors are returned as gRPC Status codes.
    ============================================================================

    """

    def ListDatabases(self, request, context):
        """List all databases with summary info.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDatabase(self, request, context):
        """Create a new named database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDatabase(self, request, context):
        """Delete a database by name. Cannot delete "default".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatabaseInfo(self, request, context):
        """Get database info (node/edge counts, metadata).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDatabases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatabases,
                    request_deserializer=gql__service__pb2.ListDatabasesRequest.FromString,
                    response_serializer=gql__service__pb2.ListDatabasesResponse.SerializeToString,
            ),
            'CreateDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDatabase,
                    request_deserializer=gql__service__pb2.CreateDatabaseRequest.FromString,
                    response_serializer=gql__service__pb2.CreateDatabaseResponse.SerializeToString,
            ),
            'DeleteDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDatabase,
                    request_deserializer=gql__service__pb2.DeleteDatabaseRequest.FromString,
                    response_serializer=gql__service__pb2.DeleteDatabaseResponse.SerializeToString,
            ),
            'GetDatabaseInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatabaseInfo,
                    request_deserializer=gql__service__pb2.GetDatabaseInfoRequest.FromString,
                    response_serializer=gql__service__pb2.GetDatabaseInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gql.DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gql.DatabaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """============================================================================
    DatabaseService
    Manages database lifecycle. Requires appropriate privileges.
    Errors are returned as gRPC Status codes.
    ============================================================================

    """

    @staticmethod
    def ListDatabases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.DatabaseService/ListDatabases',
            gql__service__pb2.ListDatabasesRequest.SerializeToString,
            gql__service__pb2.ListDatabasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.DatabaseService/CreateDatabase',
            gql__service__pb2.CreateDatabaseRequest.SerializeToString,
            gql__service__pb2.CreateDatabaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.DatabaseService/DeleteDatabase',
            gql__service__pb2.DeleteDatabaseRequest.SerializeToString,
            gql__service__pb2.DeleteDatabaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatabaseInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gql.DatabaseService/GetDatabaseInfo',
            gql__service__pb2.GetDatabaseInfoRequest.SerializeToString,
            gql__service__pb2.GetDatabaseInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
