//! Generated protobuf types and gRPC service definitions.
//!
//! Re-exports the code generated by `prost` and `tonic` from
//! `proto/gql_types.proto` and `proto/gql_service.proto`.

#![allow(
    missing_docs,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    unreachable_pub
)]

tonic::include_proto!("gql");
